### ISSUE TITLE
Missing visitor for methods

### ISSUE THREAD

**Issue by Shnatsel** [rust-fuzz/auto-fuzz-test#1]
I cannot contribute a visitor for methods defined on traits for legal issues.

Example of what an autogenerated fuzzing harness for a method could look like: https://gist.github.com/Shnatsel/4a907d44d6429de93d63d6e7c4d1361e

The structure is pretty similar to the `fn` visitor, and you already have everything in one struct without having to track context manually, see https://docs.rs/syn/0.15.26/syn/struct.ImplItemMethod.html

The printing will largely be duplicated, so it might be a good idea to split it off from the visiting.

**Comment by Shnatsel** [comment]
Other than that this looks very nice! Thanks for implementing this!

**Comment by Eh2406** [comment]
At the moment this is only doing freestanding functions, I will look into adding methods.

At the moment this is set up to take a source file and make ~70% correct `proptest boilerplate`. I would be open to seeing different modes, like `quickcheck boilerplate`, or `quickcheck afl.rs boilerplate` or anything people find useful. I know you wanted to use this to bootstrap testing std. I'd love to inspire a quick fix for intellij, right click on a function and hit "add proptest".

**Comment by Eh2406** [comment]
https://github.com/Eh2406/auto-fuzz-test/commit/324d32653bb0815b96cfa55f1cd36361199ebdfd adds the ability to transform methods. So the headline of this issue is fixed.

**Comment by Shnatsel** [comment]
I should be able to take over from here. Thanks a lot!

> I'd love to inspire a quick fix for intellij, right click on a function and hit "add proptest".

That has never occurred to me, but sounds like a good idea!
